---
title: "Resume"
---

```{r knit-resume, message=FALSE}
#| eval: false
#| include: false
rmarkdown::render(
  output_format = "pdf_document",
  output_file   = "StephanieGutierrezResume.pdf",
  output_dir    = "resume",
  quiet         = TRUE
)
```

You can view a PDF version of my resume:

```{=html}
<a href="resume/StephanieGutierrezResume.pdf" target= "_blank" class= "custom-btn"> StephanieGutierrezResume.pdf
</a>
```

# Professional Summary

Digital Marketing Masters student with extended knowledge in graphic communications and computer science, interested a full time position in the field of marketing that will allow me to utilize my skills in Hubspot, SemRuch, Tableau, and HTML to create strategic market opportunities for successful marketing campaigns.

# Technical Skills

-   **Marketing Skills:** Google Analytics, Google Tag Manager, Etsy SEO, YouTube Studio

-   **Marketing Tools:** SemRush, Moz, Tableau, and IRB Certification

-   **CRM Tools:** Salesforce, Hubspot, Asana Design

-   **Creative Tools:** Adobe (Photoshop, Illustrator, Acrobat, Dimension), Canva

-   **Video Creative Tools:** Adobe Premiere Pro and CapCut

-   **Office Software:** Microsoft Office (Word, Excel, PowerPoint, Teams, Outlook), Google Workspace (Docs, Sheets, Slides)

-   **Programming Languages/ Markdown Languages:** R, Quarto, HTML, CSS, SQL, Java

-   **Programming Tools:** GitHub, RStudio, Positron

-   **Languages:** English, Spanish

# Education

+-----------------------------+---------------+----------------------------------------------+-------------------------------------------------+
| Degree                      | Year          | College / Department                         | Institution                                     |
+=============================+===============+==============================================+=================================================+
| M.S Digital Marketing       | 20 24-2026    | Singelyn College of Business A dministration | California State Polytechnic University, Pomona |
+-----------------------------+---------------+----------------------------------------------+-------------------------------------------------+
| B.S Graphic Communication,  | 2021          | College of ECST                              | California State University, Los Angeles        |
|                             |               |                                              |                                                 |
| *Minor in Computer Science* |               |                                              |                                                 |
+-----------------------------+---------------+----------------------------------------------+-------------------------------------------------+

# Work Experience

### **Print and Marketing Supervisor \| STAPLES**

*Aug 2021 - Present*

-   Lead small business campaigns using Adobe Acrobat, Photoshop, and also using the Staples workstation
-   Send weekly Salesforce email marketing campaigns to High Value Customers
-   Train and supervise 5+ team members to ensure the weekly sales goals dashboard

------------------------------------------------------------------------

### **Digital Graphic Designer \| ETSY SELF EMPLOYED**

*Jan 2022 - Present*

-   Create and sell digital graphic templates and printable art

-   Optimizing the Etsy store through SEO and Etsy performance statistics metrics driving over 400 sales

-   Design promotional assets using Adobe Creative Suite and Canva

------------------------------------------------------------------------

# Memberships & Affiliations

**Delta Phi Epsilon (Philanthropic Sorority)** *Zeta Eta Chapter, CSULA*

-   2016 - Cystic Fibrosis Coordinator

-   2017 - Intramural Coordinator

------------------------------------------------------------------------

# Certifications

**Google Skillshop**

-   Google Analytics 4 Certification

**HubSpot Academy**

-   Inbound Marketing, Inbound Marketing Optimization, HubSpot Reporting

**SemRush Academy**

-   SEO Essentials with SemRush

**California State Polytechnic University, Pomona**

-   Data Wrangling & Visualization Certification (Online Course)
